font:
   normal:
       family: CaskaydiaCove Nerd Font Mono
       style: Regular
   size: 22
colors:
  # Default colors
  primary:
    background: '#141414'
    foreground: '#f9f9f9'
      #dim_foreground:    '#232323'
      #bright_foreground: '#f9f9f9'
      #dim_background:    '#202020' # not sure
    bright_background: '#3a3a3a' # not sure

  # Cursor colors
  cursor:
    text:   '#fcfcfc'
    cursor: '#6b6b6b'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  line_indicator:
    foreground: None
    background: None
  # Normal colors
  normal:
    black:   '#777777'
    red:     '#ff453a'
    green:   '#32d74b'
    yellow:  '#ffd60a'
    blue:    '#0a84ff'
    magenta: '#bf5af2'
    cyan:    '#5ac8fa'
    white:   '#f9f9f9'
  # Bright colors
  bright:
    black:   '#A1A1A1'
    red:     '#FF4F44'
    green:   '#3CE155'
    yellow:  '#FFE014'
    blue:    '#148EFF'
    magenta: '#CC65FF'
    cyan:    '#6EDCFF'
    white:   '#ffffff'

  # Dim colors
  dim:
    black:   '#646464'
    red:     '#F53126'
    green:   '#1EC337'
    yellow:  '#F5C200'
    blue:    '#0070F5'
    magenta: '#9F4BC9'
    cyan:    '#50BEF0'
    white:   '#fafafa'

window:
  padding:
    x: 16
    y: 16

background_opacity: 0.8
