add_newline = true

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$character\
"""

right_format = """
$sudo\
$cmd_duration\
$python\
$time"""

[directory]
truncate_to_repo = false
style = "blue"
read_only = " ro"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "white"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "white"

[git_status]
format = '[$conflicted](red)[$untracked](yellow)[$modified](magenta)[$staged](green)[$renamed](yellow)[$deleted](red)[$ahead_behind](magenta)[$stashed](white) '
style = "cyan"
conflicted = "x"
untracked = "?"
modified = ""
staged = "+"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
renamed = ""
deleted = ""
stashed = ""

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "white"

[time]
disabled = false
format = '[$time]($style)'
style = "white"
time_format = "%r" # Hour:Minute:Seconds AM/PM Format
use_12hr = true

[sudo]
style = 'bold green'
symbol = 'sudo '
disabled = false
